name: MATLAB CI

on:
  push:
    branches: [main]


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Compile MEX files
        uses: matlab-actions/run-command@v2
        with:
          command: cd Tests; run('silent_install.m')
      - name: Run unit tests
        uses: matlab-actions/run-command@v2
        with:
          command: results = runtests, assertSuccess(results)
