name: MATLAB CI

on:
  push:
    branches: [main]


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Install MATLAB toolboxes
        uses: matlab-actions/run-command@v2
        with:
           command: |
            matlab -batch "matlab.addons.toolbox.installToolbox('Statistics and Machine Learning'); 
                    matlab.addons.toolbox.installToolbox('Signal Processing'); 
                    matlab.addons.toolbox.installToolbox('Curve Fitting'); 
                    matlab.addons.toolbox.installToolbox('System Identification'); 
                    matlab.addons.toolbox.installToolbox('Wavelet'); 
                    matlab.addons.toolbox.installToolbox('Econometrics');"
      - name: Compile MEX files
        uses: matlab-actions/run-command@v1
        with:
          command: |
            matlab -batch "run('install.m');"
