name: MATLAB CI

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
  steps:
     - uses: actions/checkout@v2
     - name: Set up MATLAB
       uses: matlab-actions/setup-matlab@v1

